name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - name: publish
      uses: pennsignals/publish_docker-compose@v0.1.0
      with:
        version: '0.2.6-rc.1' # optional
        docker_compose: 'docker-compose.yml' # required
        repo_token: "${{ secrets.CR_PAT }}"

      # - name: Build and push
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: test
      #     tag: latest
      #     content: .
      #     registry: ghcr.io
      #     # githubOrg: markjeli # optional
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.CR_PAT2 }}