name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Build the stack
         run: |
           docker-compose build -d
           docker-compose push
           echo "AAAAA"