name: publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: image-name
        registry: ghcr.io
        githubOrg: override-org # optional
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
  #  - uses: docker/build-push-action@v2
  #     with:
  #      context: .
  #      tags: ghcr.io/markjeli/myapp:latest
  #      push: true

    # - name: Build the hello-world Docker image
    #   run: |
    #     docker build . --tag ghcr.io/markjeli/hello-world:latest
    #     docker push ghcr.io/markjeli/hello-world:latest