name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Build the stack
         run: |
           docker-compose build
           docker-compose push
           echo "AAAAA"